### ISSUE TITLE
Error for QL_810W - ERROR_WRONG_LABEL

### ISSUE THREAD

**Issue by gabrieltm** [PrimaelQuemerais/brother_label_print_dart#5]
When trying to run the example code in QL_810W model, i'm getting the following error:

E/BROTHER PRINTER ERROR(32193): ERROR_WRONG_LABEL

**Comment by PrimaelQuemerais** [comment]
ERROR_WRONG_LABEL : This error can occur either if the selected templateKey doesn't exist on the printer or if the paperSize doesn't match with the labels used.
Can you check both of those ? The paperSize variable is not implemented yet, what kind of labels are you using ?
I do not own the printer anymore but if your willing to help me debugging it I can implement the missing functionalities.

**Comment by gabrieltm** [comment]
Hi @PrimaelQuemerais ! First, thanks for the fast reply.

I'm not sure where I can find the templateKey information, but the label I'm using is a 62mm one. I tried searching at StackOverflow and some people are having the same issue with the QL_810W model - https://stackoverflow.com/a/55221373/5905500
I tried changing mLabelInfo.labelNameIndex to different values (0 to 50) but got no success.

I can for sure help you debug and test, but I'm not very experienced with kotlin or dart lang, but I can definitely try!

**Comment by PrimaelQuemerais** [comment]
You need to load a template on the printer first using the Brother pc software (it should be possible to do it via the app but I didn't have the time to look into yet). The software will also let you know the templateIndex, normaly the first label you load will have an index of 1.
We can take a further look into it if you still can't get it to work :slightly_smiling_face:

**Comment by gabrieltm** [comment]
I tried creating a template using P-touch, as the image below, I assigned key 5 to it.

![image](https://user-images.githubusercontent.com/5482240/85950914-0adf4b80-b936-11ea-82ef-f75de4979b34.png)

I made no changes to the code: 

    if (bulk) {
      for (int i = 0; i < 5; i++) {
        labels.add(TemplateLabel(i < 3 ? 1 : 2, [
          "0 : Label $i",
          "1 : 31/03/2020 - 12:00",
          "2 : Primael.Q",
          "3 : 02/04/2020",
          "4 : 03/04/2020",
          "5 : 12:00",
          "6 : 12:00"
        ]));
      }
    } else {
      labels.add(TemplateLabel(1, [
        "0 : Cheddar Mozzarella Rapé",
        "1 : 31/03/2020 - 12:00",
        "2 : Primael.Q",
        "3 : 02/04/2020",
        "4 : 03/04/2020",
        "5 : 12:00",
        "6 : 12:00"
      ]));
    }

    String result;
    try {
      result = await Brotherlabelprintdart.printLabelFromTemplate(
          "192.168.118.1", PrinterModel.QL_810W, labels);
    } catch (e) {
      result = "An error occured : $e";
    }

What I'm trying to create is an app that creates custom visitor badges (based on user input). So I need to send some data from my app to print it.

**Comment by PrimaelQuemerais** [comment]
Does your template have 7 fields ? I'm not sure but maybe that can cause an issue.

**Comment by gabrieltm** [comment]
Changed to one field only

![image](https://user-images.githubusercontent.com/5482240/85951410-7971d880-b939-11ea-8f36-094bb20bb8a1.png)

Changed templateKey to 5

    if (bulk) {
      for (int i = 0; i < 5; i++) {
        labels.add(TemplateLabel(i < 3 ? 1 : 2, [
          "0 : Label $i",
          "1 : 31/03/2020 - 12:00",
          "2 : Primael.Q",
          "3 : 02/04/2020",
          "4 : 03/04/2020",
          "5 : 12:00",
          "6 : 12:00"
        ]));
      }
    } else {
      labels.add(TemplateLabel(5, [
        "0 : Cheddar Mozzarella Rapé",
      ]));
    }

It worked!
I will try later with more labels to see if it works, I will see if I can pass an image to it too.

Thanks a lot.

**Comment by PrimaelQuemerais** [comment]
Great !
Glad I was able to help. Images are not supported by the plugin yet but if you have the time to write the code for it feel free to create a pull request ;)
